### ISSUE TITLE
Order model showing order is not valid

### ISSUE THREAD

**Issue by Soumalya1857** [Soumalya1857/GoKraft#4]
Can anyone solve this issue? Admin site verification and authorization not working properly

**Comment by arkosen123** [comment]
I have good knowledge in this one, I can help you in this.

**Comment by Soumalya1857** [comment]
Hey I think you have missed some points...it's not fixed
Still getting error 420

**Comment by Soumalya1857** [comment]
Sorry from my side. Cool PR
